### ISSUE TITLE
Fix overview

### ISSUE THREAD

**Issue by kingonly** [breez/breez-sdk-rustdoc#1]
Use the same overview as the SDK readme: https://github.com/breez/breez-sdk

A few comments:
* The SDK isn't for building Lightning applications. It's for integrating Lightning payments in any app.
* Use 'Lightning' instead of 'LN'.
* It's not 'LSP Management', It's 'Connecting to an LSP'.
* Move "On initializing the SDK, the caller gets its [GreenlightCredentials](https://breez.github.io/breez-sdk-rustdoc/doc/breez_sdk_core/struct.GreenlightCredentials.html). These are used to interact with the Greenlight LN node running in the cloud. Together with the BIP39 mnemonic, these can be used to restore access to the same cloud node, either in the same app (backup / restore) or in another app using the SDK." outside the overview. Should be in the initialization section.

**Comment by ok300** [comment]
Done
